apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: aws-auth 
data: 
  mapUsers: | 
    - userarn: arn:aws:iam::944456950944:user/Athreya
      username: Athreya
      groups:
        - system:masters