apiVersion: v1
kind: Service
metadata:
  name: github-actions
  labels:
    app: simple-app
spec:
  type: LoadBalancer
  selector:
    app: simple-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
