name: deployment

on: [push]

permissions:
  id-token: write # This is required for requesting the JWT


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' #caching pip dependencies
          
      - run: |
            python -m pip install --upgrade pip
            if [-f requirements.txt]; then pip install -r requirements.txt; fi

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::944456950944:role/github-aws
          aws-region: ap-south-1
      
      - name: Install kubectl
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: get pods
        
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: 'true'

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: github_actions
          IMAGE_TAG: ${{ github.ref_name }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Update kube configure   
        run: aws eks update-kubeconfig --name github-actions  --region ap-south-1

      - name: Deploy to EKS 
        run: |
            kubectl apply -f deployment.yaml
            kubectl apply -f service.yaml  
